### ISSUE TITLE
Window.displayWindow

### ISSUE THREAD

**Issue by IsaacPacht** [fine-code/DashboardProject#10]
Are these lines necessary?  What happens without them?

     frame.setLocationByPlatform(true);
     frame.pack();

https://github.com/fine-code/DashboardProject/blob/e78220c7cb64ef1f4f61169981df1f4f36041e18/Window.java#L65

**Comment by fine-code** [comment]
Yes we tested it out and saw that we needed the frame.pack() and not the frame.setLocationByPlatform(true).
