### ISSUE TITLE
Reaction class

### ISSUE THREAD

**Issue by IsaacPacht** [fine-code/DashboardProject#4]
1. Field can be final
2. What if the input string doesn't match either "like" or "dislike"?
3. Is there any reason we have to allow for upper and lower case?  Do we know which one, in practice, the code will be called with?

https://github.com/fine-code/DashboardProject/blob/e78220c7cb64ef1f4f61169981df1f4f36041e18/Reaction.java#L4

**Comment by fine-code** [comment]
changed Reaction.java to an enum class
